//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationBuilder.BLL
{
  using System;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;

  public partial class PresentationBuilderEntities : DbContext
  {
    public PresentationBuilderEntities()
        : base("name=PresentationBuilderEntities")
    {
      //Assuming the PBData file is in the users MyDocuments folder
      var file = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + @"\PBData.sqlite";
      if (!System.IO.File.Exists(file))
        throw new Exception($"Data file not found: { file }");
      else
        Database.Connection.ConnectionString = $"data source={ file };DateTimeFormat=InvariantCulture;foreign keys=true";
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Book> Books { get; set; }
    public virtual DbSet<Message> Messages { get; set; }
    public virtual DbSet<MessageType> MessageTypes { get; set; }
    public virtual DbSet<Song> Songs { get; set; }
    public virtual DbSet<Verse> Verses { get; set; }
  }
}
