//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationBuilder.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verse
    {
        public int VerseID { get; set; }
        public int SongID { get; set; }
        public byte VerseNumber { get; set; }
        public string Text { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
