// Decompiled with JetBrains decompiler
// Type: PEC.Windows.Common.Dialogs.ReportPreviewRibbonDialog
// Assembly: PEC.Windows.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ed425d74cb6df699
// MVID: CDBD3A57-B7D2-4B12-ADDA-3F67C481AC77
// Assembly location: C:\oaisd_app\_Misc\Presentation Builder\EXE\PEC.Windows.Common.dll

using DevExpress.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraPrinting;
using DevExpress.XtraPrinting.Control;
using DevExpress.XtraPrinting.Preview;
using DevExpress.XtraReports.UI;
using PEC.Configuration;
using PEC.Windows.Common;
using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace PEC.Windows.Common.Dialogs
{
  public class ReportPreviewRibbonDialog : RibbonForm
  {
    private string _reportName = (string) null;
    private IContainer components = (IContainer) null;
    private XtraReport _xtraReport;
    private RibbonControl ribbon;
    private RibbonStatusBar ribbonStatusBar;
    private PanelControl clientPanel;
    private PrintPreviewBarItem printPreviewBarItem1;
    private PrintRibbonController printRibbonController1;
    private PrintControl printControl1;
    private PrintPreviewStaticItem printPreviewStaticItem1;
    private BarStaticItem barStaticItem1;
    private ProgressBarEditItem progressBarEditItem1;
    private RepositoryItemProgressBar repositoryItemProgressBar1;
    private PrintPreviewBarItem printPreviewBarItem46;
    private BarButtonItem barButtonItem1;
    private PrintPreviewStaticItem printPreviewStaticItem2;
    private ZoomTrackBarEditItem zoomTrackBarEditItem1;
    private RepositoryItemZoomTrackBar repositoryItemZoomTrackBar1;
    private PrintPreviewBarItem printPreviewBarItem2;
    private PrintPreviewBarItem printPreviewBarItem3;
    private PrintPreviewBarItem printPreviewBarItem4;
    private PrintPreviewBarItem printPreviewBarItem5;
    private PrintPreviewBarItem printPreviewBarItem6;
    private PrintPreviewBarItem printPreviewBarItem7;
    private PrintPreviewBarItem printPreviewBarItem8;
    private PrintPreviewBarItem printPreviewBarItem9;
    private PrintPreviewBarItem printPreviewBarItem10;
    private PrintPreviewBarItem printPreviewBarItem11;
    private PrintPreviewBarItem printPreviewBarItem12;
    private PrintPreviewBarItem printPreviewBarItem13;
    private PrintPreviewBarItem printPreviewBarItem14;
    private PrintPreviewBarItem printPreviewBarItem15;
    private PrintPreviewBarItem printPreviewBarItem16;
    private PrintPreviewBarItem printPreviewBarItem17;
    private PrintPreviewBarItem printPreviewBarItem18;
    private PrintPreviewBarItem printPreviewBarItem19;
    private PrintPreviewBarItem printPreviewBarItem20;
    private PrintPreviewBarItem printPreviewBarItem21;
    private PrintPreviewBarItem printPreviewBarItem22;
    private PrintPreviewBarItem printPreviewBarItem23;
    private PrintPreviewBarItem printPreviewBarItem24;
    private PrintPreviewBarItem printPreviewBarItem25;
    private PrintPreviewBarItem printPreviewBarItem26;
    private PrintPreviewBarItem printPreviewBarItem27;
    private PrintPreviewBarItem printPreviewBarItem28;
    private PrintPreviewBarItem printPreviewBarItem29;
    private PrintPreviewBarItem printPreviewBarItem30;
    private PrintPreviewBarItem printPreviewBarItem31;
    private PrintPreviewBarItem printPreviewBarItem32;
    private PrintPreviewBarItem printPreviewBarItem33;
    private PrintPreviewBarItem printPreviewBarItem34;
    private PrintPreviewBarItem printPreviewBarItem35;
    private PrintPreviewBarItem printPreviewBarItem36;
    private PrintPreviewBarItem printPreviewBarItem37;
    private PrintPreviewBarItem printPreviewBarItem38;
    private PrintPreviewBarItem printPreviewBarItem39;
    private PrintPreviewBarItem printPreviewBarItem40;
    private PrintPreviewBarItem printPreviewBarItem41;
    private PrintPreviewBarItem printPreviewBarItem42;
    private PrintPreviewBarItem printPreviewBarItem43;
    private PrintPreviewBarItem printPreviewBarItem44;
    private PrintPreviewBarItem printPreviewBarItem45;
    private PrintPreviewRibbonPage printPreviewRibbonPage1;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup1;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup2;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup3;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup4;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup5;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup6;
    private PrintPreviewRibbonPageGroup printPreviewRibbonPageGroup7;

    public ReportPreviewRibbonDialog()
    {
      this.InitializeComponent();
      ConfigurationManager.LoadFormBounds((Form) this);
    }

    protected override void OnClosing(CancelEventArgs e)
    {
      base.OnClosing(e);
      ConfigurationManager.SaveFormBounds((Form) this);
    }

    public bool LoadReport(MemoryStream reportStream, object dataSource, string reportName)
    {
      return this.LoadReport(reportStream, dataSource, reportName, (object[]) null);
    }

    public bool LoadReport(MemoryStream reportStream, object dataSource, string reportName, object[] reportParameters)
    {
      this._reportName = reportName;
      this.Text = "Preview - " + this._reportName;
      if ((ulong) reportStream.Length <= 0UL)
        return false;
      this._xtraReport = new XtraReport();
      this._xtraReport.LoadLayout((Stream) reportStream);
      this._xtraReport.Name = reportName.Replace(" ", "");
      if (reportParameters != null)
      {
        if (reportParameters.Length > this._xtraReport.Parameters.Count)
          throw new Exception("The number of parameters passed exceeds the number of parameters in the report.");
        int index = 0;
        foreach (object obj in reportParameters)
        {
          this._xtraReport.Parameters[index].Value = obj;
          ++index;
        }
      }
      reportStream.Close();
      this.SetupReport(dataSource, reportName);
      return true;
    }

    private void SetupReport(object dataSource, string reportName)
    {
      this._xtraReport.DataSource = dataSource;
      this._xtraReport.Name = reportName.Replace(" ", "").Replace("-", "");
      this.printControl1.PrintingSystem = this._xtraReport.PrintingSystem;
      this._xtraReport.CreateDocument();
      this._xtraReport.CreateDocument();
      this.printControl1.PrintingSystem = this._xtraReport.PrintingSystem;
      this.printControl1.PrintingSystem.SetCommandVisibility(new PrintingSystemCommand[7]
      {
        PrintingSystemCommand.Open,
        PrintingSystemCommand.Save,
        PrintingSystemCommand.Background,
        PrintingSystemCommand.Open,
        PrintingSystemCommand.Scale,
        PrintingSystemCommand.EditPageHF,
        PrintingSystemCommand.SendFile
      }, CommandVisibility.None);
      this.printPreviewRibbonPageGroup1.Visible = false;
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      SuperToolTip superToolTip1 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem1 = new ToolTipTitleItem();
      ToolTipItem toolTipItem1 = new ToolTipItem();
      SuperToolTip superToolTip2 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem2 = new ToolTipTitleItem();
      ToolTipItem toolTipItem2 = new ToolTipItem();
      SuperToolTip superToolTip3 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem3 = new ToolTipTitleItem();
      ToolTipItem toolTipItem3 = new ToolTipItem();
      SuperToolTip superToolTip4 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem4 = new ToolTipTitleItem();
      ToolTipItem toolTipItem4 = new ToolTipItem();
      SuperToolTip superToolTip5 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem5 = new ToolTipTitleItem();
      ToolTipItem toolTipItem5 = new ToolTipItem();
      SuperToolTip superToolTip6 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem6 = new ToolTipTitleItem();
      ToolTipItem toolTipItem6 = new ToolTipItem();
      SuperToolTip superToolTip7 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem7 = new ToolTipTitleItem();
      ToolTipItem toolTipItem7 = new ToolTipItem();
      SuperToolTip superToolTip8 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem8 = new ToolTipTitleItem();
      ToolTipItem toolTipItem8 = new ToolTipItem();
      SuperToolTip superToolTip9 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem9 = new ToolTipTitleItem();
      ToolTipItem toolTipItem9 = new ToolTipItem();
      SuperToolTip superToolTip10 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem10 = new ToolTipTitleItem();
      ToolTipItem toolTipItem10 = new ToolTipItem();
      SuperToolTip superToolTip11 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem11 = new ToolTipTitleItem();
      ToolTipItem toolTipItem11 = new ToolTipItem();
      SuperToolTip superToolTip12 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem12 = new ToolTipTitleItem();
      ToolTipItem toolTipItem12 = new ToolTipItem();
      SuperToolTip superToolTip13 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem13 = new ToolTipTitleItem();
      ToolTipItem toolTipItem13 = new ToolTipItem();
      SuperToolTip superToolTip14 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem14 = new ToolTipTitleItem();
      ToolTipItem toolTipItem14 = new ToolTipItem();
      SuperToolTip superToolTip15 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem15 = new ToolTipTitleItem();
      ToolTipItem toolTipItem15 = new ToolTipItem();
      SuperToolTip superToolTip16 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem16 = new ToolTipTitleItem();
      ToolTipItem toolTipItem16 = new ToolTipItem();
      SuperToolTip superToolTip17 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem17 = new ToolTipTitleItem();
      ToolTipItem toolTipItem17 = new ToolTipItem();
      SuperToolTip superToolTip18 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem18 = new ToolTipTitleItem();
      ToolTipItem toolTipItem18 = new ToolTipItem();
      SuperToolTip superToolTip19 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem19 = new ToolTipTitleItem();
      ToolTipItem toolTipItem19 = new ToolTipItem();
      SuperToolTip superToolTip20 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem20 = new ToolTipTitleItem();
      ToolTipItem toolTipItem20 = new ToolTipItem();
      SuperToolTip superToolTip21 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem21 = new ToolTipTitleItem();
      ToolTipItem toolTipItem21 = new ToolTipItem();
      SuperToolTip superToolTip22 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem22 = new ToolTipTitleItem();
      ToolTipItem toolTipItem22 = new ToolTipItem();
      SuperToolTip superToolTip23 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem23 = new ToolTipTitleItem();
      ToolTipItem toolTipItem23 = new ToolTipItem();
      SuperToolTip superToolTip24 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem24 = new ToolTipTitleItem();
      ToolTipItem toolTipItem24 = new ToolTipItem();
      SuperToolTip superToolTip25 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem25 = new ToolTipTitleItem();
      ToolTipItem toolTipItem25 = new ToolTipItem();
      SuperToolTip superToolTip26 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem26 = new ToolTipTitleItem();
      ToolTipItem toolTipItem26 = new ToolTipItem();
      SuperToolTip superToolTip27 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem27 = new ToolTipTitleItem();
      ToolTipItem toolTipItem27 = new ToolTipItem();
      SuperToolTip superToolTip28 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem28 = new ToolTipTitleItem();
      ToolTipItem toolTipItem28 = new ToolTipItem();
      SuperToolTip superToolTip29 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem29 = new ToolTipTitleItem();
      ToolTipItem toolTipItem29 = new ToolTipItem();
      SuperToolTip superToolTip30 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem30 = new ToolTipTitleItem();
      ToolTipItem toolTipItem30 = new ToolTipItem();
      SuperToolTip superToolTip31 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem31 = new ToolTipTitleItem();
      ToolTipItem toolTipItem31 = new ToolTipItem();
      SuperToolTip superToolTip32 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem32 = new ToolTipTitleItem();
      ToolTipItem toolTipItem32 = new ToolTipItem();
      SuperToolTip superToolTip33 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem33 = new ToolTipTitleItem();
      ToolTipItem toolTipItem33 = new ToolTipItem();
      SuperToolTip superToolTip34 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem34 = new ToolTipTitleItem();
      ToolTipItem toolTipItem34 = new ToolTipItem();
      SuperToolTip superToolTip35 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem35 = new ToolTipTitleItem();
      ToolTipItem toolTipItem35 = new ToolTipItem();
      SuperToolTip superToolTip36 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem36 = new ToolTipTitleItem();
      ToolTipItem toolTipItem36 = new ToolTipItem();
      SuperToolTip superToolTip37 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem37 = new ToolTipTitleItem();
      ToolTipItem toolTipItem37 = new ToolTipItem();
      SuperToolTip superToolTip38 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem38 = new ToolTipTitleItem();
      ToolTipItem toolTipItem38 = new ToolTipItem();
      SuperToolTip superToolTip39 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem39 = new ToolTipTitleItem();
      ToolTipItem toolTipItem39 = new ToolTipItem();
      SuperToolTip superToolTip40 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem40 = new ToolTipTitleItem();
      ToolTipItem toolTipItem40 = new ToolTipItem();
      SuperToolTip superToolTip41 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem41 = new ToolTipTitleItem();
      ToolTipItem toolTipItem41 = new ToolTipItem();
      SuperToolTip superToolTip42 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem42 = new ToolTipTitleItem();
      ToolTipItem toolTipItem42 = new ToolTipItem();
      SuperToolTip superToolTip43 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem43 = new ToolTipTitleItem();
      ToolTipItem toolTipItem43 = new ToolTipItem();
      SuperToolTip superToolTip44 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem44 = new ToolTipTitleItem();
      ToolTipItem toolTipItem44 = new ToolTipItem();
      SuperToolTip superToolTip45 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem45 = new ToolTipTitleItem();
      ToolTipItem toolTipItem45 = new ToolTipItem();
      SuperToolTip superToolTip46 = new SuperToolTip();
      ToolTipTitleItem toolTipTitleItem46 = new ToolTipTitleItem();
      ToolTipItem toolTipItem46 = new ToolTipItem();
      this.ribbon = new RibbonControl();
      this.printPreviewBarItem1 = new PrintPreviewBarItem();
      this.printRibbonController1 = new PrintRibbonController();
      this.printControl1 = new PrintControl();
      this.ribbonStatusBar = new RibbonStatusBar();
      this.printPreviewStaticItem1 = new PrintPreviewStaticItem();
      this.barStaticItem1 = new BarStaticItem();
      this.progressBarEditItem1 = new ProgressBarEditItem();
      this.repositoryItemProgressBar1 = new RepositoryItemProgressBar();
      this.printPreviewBarItem46 = new PrintPreviewBarItem();
      this.barButtonItem1 = new BarButtonItem();
      this.printPreviewStaticItem2 = new PrintPreviewStaticItem();
      this.zoomTrackBarEditItem1 = new ZoomTrackBarEditItem();
      this.repositoryItemZoomTrackBar1 = new RepositoryItemZoomTrackBar();
      this.printPreviewBarItem2 = new PrintPreviewBarItem();
      this.printPreviewBarItem3 = new PrintPreviewBarItem();
      this.printPreviewBarItem4 = new PrintPreviewBarItem();
      this.printPreviewBarItem5 = new PrintPreviewBarItem();
      this.printPreviewBarItem6 = new PrintPreviewBarItem();
      this.printPreviewBarItem7 = new PrintPreviewBarItem();
      this.printPreviewBarItem8 = new PrintPreviewBarItem();
      this.printPreviewBarItem9 = new PrintPreviewBarItem();
      this.printPreviewBarItem10 = new PrintPreviewBarItem();
      this.printPreviewBarItem11 = new PrintPreviewBarItem();
      this.printPreviewBarItem12 = new PrintPreviewBarItem();
      this.printPreviewBarItem13 = new PrintPreviewBarItem();
      this.printPreviewBarItem14 = new PrintPreviewBarItem();
      this.printPreviewBarItem15 = new PrintPreviewBarItem();
      this.printPreviewBarItem16 = new PrintPreviewBarItem();
      this.printPreviewBarItem17 = new PrintPreviewBarItem();
      this.printPreviewBarItem18 = new PrintPreviewBarItem();
      this.printPreviewBarItem19 = new PrintPreviewBarItem();
      this.printPreviewBarItem20 = new PrintPreviewBarItem();
      this.printPreviewBarItem21 = new PrintPreviewBarItem();
      this.printPreviewBarItem22 = new PrintPreviewBarItem();
      this.printPreviewBarItem23 = new PrintPreviewBarItem();
      this.printPreviewBarItem24 = new PrintPreviewBarItem();
      this.printPreviewBarItem25 = new PrintPreviewBarItem();
      this.printPreviewBarItem26 = new PrintPreviewBarItem();
      this.printPreviewBarItem27 = new PrintPreviewBarItem();
      this.printPreviewBarItem28 = new PrintPreviewBarItem();
      this.printPreviewBarItem29 = new PrintPreviewBarItem();
      this.printPreviewBarItem30 = new PrintPreviewBarItem();
      this.printPreviewBarItem31 = new PrintPreviewBarItem();
      this.printPreviewBarItem32 = new PrintPreviewBarItem();
      this.printPreviewBarItem33 = new PrintPreviewBarItem();
      this.printPreviewBarItem34 = new PrintPreviewBarItem();
      this.printPreviewBarItem35 = new PrintPreviewBarItem();
      this.printPreviewBarItem36 = new PrintPreviewBarItem();
      this.printPreviewBarItem37 = new PrintPreviewBarItem();
      this.printPreviewBarItem38 = new PrintPreviewBarItem();
      this.printPreviewBarItem39 = new PrintPreviewBarItem();
      this.printPreviewBarItem40 = new PrintPreviewBarItem();
      this.printPreviewBarItem41 = new PrintPreviewBarItem();
      this.printPreviewBarItem42 = new PrintPreviewBarItem();
      this.printPreviewBarItem43 = new PrintPreviewBarItem();
      this.printPreviewBarItem44 = new PrintPreviewBarItem();
      this.printPreviewBarItem45 = new PrintPreviewBarItem();
      this.printPreviewRibbonPage1 = new PrintPreviewRibbonPage();
      this.printPreviewRibbonPageGroup1 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup2 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup3 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup4 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup5 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup6 = new PrintPreviewRibbonPageGroup();
      this.printPreviewRibbonPageGroup7 = new PrintPreviewRibbonPageGroup();
      this.clientPanel = new PanelControl();
      this.printRibbonController1.BeginInit();
      this.repositoryItemProgressBar1.BeginInit();
      this.repositoryItemZoomTrackBar1.BeginInit();
      this.clientPanel.BeginInit();
      this.clientPanel.SuspendLayout();
      this.SuspendLayout();
      this.ribbon.ApplicationButtonKeyTip = "";
      this.ribbon.ApplicationIcon = (Bitmap) null;
      this.ribbon.Items.AddRange(new BarItem[52]
      {
        (BarItem) this.printPreviewBarItem1,
        (BarItem) this.printPreviewBarItem2,
        (BarItem) this.printPreviewBarItem3,
        (BarItem) this.printPreviewBarItem4,
        (BarItem) this.printPreviewBarItem5,
        (BarItem) this.printPreviewBarItem6,
        (BarItem) this.printPreviewBarItem7,
        (BarItem) this.printPreviewBarItem8,
        (BarItem) this.printPreviewBarItem9,
        (BarItem) this.printPreviewBarItem10,
        (BarItem) this.printPreviewBarItem11,
        (BarItem) this.printPreviewBarItem12,
        (BarItem) this.printPreviewBarItem13,
        (BarItem) this.printPreviewBarItem14,
        (BarItem) this.printPreviewBarItem15,
        (BarItem) this.printPreviewBarItem16,
        (BarItem) this.printPreviewBarItem17,
        (BarItem) this.printPreviewBarItem18,
        (BarItem) this.printPreviewBarItem19,
        (BarItem) this.printPreviewBarItem20,
        (BarItem) this.printPreviewBarItem21,
        (BarItem) this.printPreviewBarItem22,
        (BarItem) this.printPreviewBarItem23,
        (BarItem) this.printPreviewBarItem24,
        (BarItem) this.printPreviewBarItem25,
        (BarItem) this.printPreviewBarItem26,
        (BarItem) this.printPreviewBarItem27,
        (BarItem) this.printPreviewBarItem28,
        (BarItem) this.printPreviewBarItem29,
        (BarItem) this.printPreviewBarItem30,
        (BarItem) this.printPreviewBarItem31,
        (BarItem) this.printPreviewBarItem32,
        (BarItem) this.printPreviewBarItem33,
        (BarItem) this.printPreviewBarItem34,
        (BarItem) this.printPreviewBarItem35,
        (BarItem) this.printPreviewBarItem36,
        (BarItem) this.printPreviewBarItem37,
        (BarItem) this.printPreviewBarItem38,
        (BarItem) this.printPreviewBarItem39,
        (BarItem) this.printPreviewBarItem40,
        (BarItem) this.printPreviewBarItem41,
        (BarItem) this.printPreviewBarItem42,
        (BarItem) this.printPreviewBarItem43,
        (BarItem) this.printPreviewBarItem44,
        (BarItem) this.printPreviewBarItem45,
        (BarItem) this.printPreviewStaticItem1,
        (BarItem) this.barStaticItem1,
        (BarItem) this.progressBarEditItem1,
        (BarItem) this.printPreviewBarItem46,
        (BarItem) this.barButtonItem1,
        (BarItem) this.printPreviewStaticItem2,
        (BarItem) this.zoomTrackBarEditItem1
      });
      this.ribbon.Location = new Point(0, 0);
      this.ribbon.MaxItemId = 52;
      this.ribbon.Name = "ribbon";
      this.ribbon.Pages.AddRange(new RibbonPage[1]
      {
        (RibbonPage) this.printPreviewRibbonPage1
      });
      this.ribbon.RepositoryItems.AddRange(new RepositoryItem[2]
      {
        (RepositoryItem) this.repositoryItemProgressBar1,
        (RepositoryItem) this.repositoryItemZoomTrackBar1
      });
      this.ribbon.SelectedPage = (RibbonPage) this.printPreviewRibbonPage1;
      this.ribbon.Size = new Size(889, 143);
      this.ribbon.StatusBar = this.ribbonStatusBar;
      this.ribbon.TransparentEditors = true;
      this.printPreviewBarItem1.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem1.Caption = "Bookmarks";
      this.printPreviewBarItem1.Command = PrintingSystemCommand.DocumentMap;
      this.printPreviewBarItem1.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem1.Enabled = false;
      this.printPreviewBarItem1.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_DocumentMap;
      this.printPreviewBarItem1.Id = 0;
      this.printPreviewBarItem1.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_DocumentMapLarge;
      this.printPreviewBarItem1.Name = "printPreviewBarItem1";
      superToolTip1.FixedTooltipWidth = true;
      toolTipTitleItem1.Text = "Document Map";
      toolTipItem1.LeftIndent = 6;
      toolTipItem1.Text = "Open the Document Map, which allows you to navigate through a structural view of the document.";
      superToolTip1.Items.Add((BaseToolTipItem) toolTipTitleItem1);
      superToolTip1.Items.Add((BaseToolTipItem) toolTipItem1);
      superToolTip1.MaxWidth = 210;
      this.printPreviewBarItem1.SuperTip = superToolTip1;
      this.printRibbonController1.PrintControl = this.printControl1;
      this.printRibbonController1.RibbonControl = this.ribbon;
      this.printRibbonController1.RibbonStatusBar = this.ribbonStatusBar;
      this.printControl1.BackColor = Color.Empty;
      this.printControl1.Dock = DockStyle.Fill;
      this.printControl1.ForeColor = Color.Empty;
      this.printControl1.IsMetric = false;
      this.printControl1.Location = new Point(0, 0);
      this.printControl1.Name = "printControl1";
      this.printControl1.Size = new Size(889, 439);
      this.printControl1.TabIndex = 0;
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.printPreviewStaticItem1);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.barStaticItem1, true);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.progressBarEditItem1);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.printPreviewBarItem46);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.barButtonItem1);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.printPreviewStaticItem2);
      this.ribbonStatusBar.ItemLinks.Add((BarItem) this.zoomTrackBarEditItem1);
      this.ribbonStatusBar.Location = new Point(0, 582);
      this.ribbonStatusBar.Name = "ribbonStatusBar";
      this.ribbonStatusBar.Ribbon = this.ribbon;
      this.ribbonStatusBar.Size = new Size(889, 25);
      this.printPreviewStaticItem1.Caption = "Page 0 of 0";
      this.printPreviewStaticItem1.Id = 45;
      this.printPreviewStaticItem1.LeftIndent = 1;
      this.printPreviewStaticItem1.Name = "printPreviewStaticItem1";
      this.printPreviewStaticItem1.RightIndent = 1;
      this.printPreviewStaticItem1.TextAlignment = StringAlignment.Near;
      this.printPreviewStaticItem1.Type = "PageOfPages";
      this.barStaticItem1.Id = 46;
      this.barStaticItem1.Name = "barStaticItem1";
      this.barStaticItem1.TextAlignment = StringAlignment.Near;
      this.progressBarEditItem1.ContextSpecifier = (object) this.printRibbonController1;
      this.progressBarEditItem1.Edit = (RepositoryItem) this.repositoryItemProgressBar1;
      this.progressBarEditItem1.EditHeight = 12;
      this.progressBarEditItem1.Id = 47;
      this.progressBarEditItem1.Name = "progressBarEditItem1";
      this.progressBarEditItem1.Visibility = BarItemVisibility.Never;
      this.progressBarEditItem1.Width = 150;
      this.repositoryItemProgressBar1.Name = "repositoryItemProgressBar1";
      this.repositoryItemProgressBar1.UseParentBackground = true;
      this.printPreviewBarItem46.Caption = "Stop";
      this.printPreviewBarItem46.Command = PrintingSystemCommand.StopPageBuilding;
      this.printPreviewBarItem46.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem46.Enabled = false;
      this.printPreviewBarItem46.Hint = "Stop";
      this.printPreviewBarItem46.Id = 48;
      this.printPreviewBarItem46.Name = "printPreviewBarItem46";
      this.printPreviewBarItem46.Visibility = BarItemVisibility.Never;
      this.barButtonItem1.Alignment = BarItemLinkAlignment.Left;
      this.barButtonItem1.Enabled = false;
      this.barButtonItem1.Id = 49;
      this.barButtonItem1.Name = "barButtonItem1";
      this.printPreviewStaticItem2.Alignment = BarItemLinkAlignment.Right;
      this.printPreviewStaticItem2.Caption = "100%";
      this.printPreviewStaticItem2.Id = 50;
      this.printPreviewStaticItem2.Name = "printPreviewStaticItem2";
      this.printPreviewStaticItem2.TextAlignment = StringAlignment.Near;
      this.printPreviewStaticItem2.Type = "ZoomFactorText";
      this.printPreviewStaticItem2.Width = 40;
      this.zoomTrackBarEditItem1.Alignment = BarItemLinkAlignment.Right;
      this.zoomTrackBarEditItem1.ContextSpecifier = (object) this.printRibbonController1;
      this.zoomTrackBarEditItem1.Edit = (RepositoryItem) this.repositoryItemZoomTrackBar1;
      this.zoomTrackBarEditItem1.EditValue = (object) 90;
      this.zoomTrackBarEditItem1.Enabled = false;
      this.zoomTrackBarEditItem1.Id = 51;
      this.zoomTrackBarEditItem1.Name = "zoomTrackBarEditItem1";
      this.zoomTrackBarEditItem1.Width = 140;
      this.repositoryItemZoomTrackBar1.AllowFocused = false;
      this.repositoryItemZoomTrackBar1.BorderStyle = BorderStyles.NoBorder;
      this.repositoryItemZoomTrackBar1.Maximum = 180;
      this.repositoryItemZoomTrackBar1.Name = "repositoryItemZoomTrackBar1";
      this.repositoryItemZoomTrackBar1.ScrollThumbStyle = ScrollThumbStyle.ArrowDownRight;
      this.repositoryItemZoomTrackBar1.UseParentBackground = true;
      this.printPreviewBarItem2.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem2.Caption = "Parameters";
      this.printPreviewBarItem2.Command = PrintingSystemCommand.Parameters;
      this.printPreviewBarItem2.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem2.Enabled = false;
      this.printPreviewBarItem2.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Parameters;
      this.printPreviewBarItem2.Id = 1;
      this.printPreviewBarItem2.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ParametersLarge;
      this.printPreviewBarItem2.Name = "printPreviewBarItem2";
      superToolTip2.FixedTooltipWidth = true;
      toolTipTitleItem2.Text = "Parameters";
      toolTipItem2.LeftIndent = 6;
      toolTipItem2.Text = "Open the Parameters pane, which allows you to enter values for report parameters.";
      superToolTip2.Items.Add((BaseToolTipItem) toolTipTitleItem2);
      superToolTip2.Items.Add((BaseToolTipItem) toolTipItem2);
      superToolTip2.MaxWidth = 210;
      this.printPreviewBarItem2.SuperTip = superToolTip2;
      this.printPreviewBarItem3.Caption = "Find";
      this.printPreviewBarItem3.Command = PrintingSystemCommand.Find;
      this.printPreviewBarItem3.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem3.Enabled = false;
      this.printPreviewBarItem3.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Find;
      this.printPreviewBarItem3.Id = 2;
      this.printPreviewBarItem3.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_FindLarge;
      this.printPreviewBarItem3.Name = "printPreviewBarItem3";
      superToolTip3.FixedTooltipWidth = true;
      toolTipTitleItem3.Text = "Find";
      toolTipItem3.LeftIndent = 6;
      toolTipItem3.Text = "Show the Find dialog to find text in the document.";
      superToolTip3.Items.Add((BaseToolTipItem) toolTipTitleItem3);
      superToolTip3.Items.Add((BaseToolTipItem) toolTipItem3);
      superToolTip3.MaxWidth = 210;
      this.printPreviewBarItem3.SuperTip = superToolTip3;
      this.printPreviewBarItem4.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem4.Caption = "Options";
      this.printPreviewBarItem4.Command = PrintingSystemCommand.Customize;
      this.printPreviewBarItem4.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem4.Enabled = false;
      this.printPreviewBarItem4.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Customize;
      this.printPreviewBarItem4.Id = 3;
      this.printPreviewBarItem4.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_CustomizeLarge;
      this.printPreviewBarItem4.Name = "printPreviewBarItem4";
      superToolTip4.FixedTooltipWidth = true;
      toolTipTitleItem4.Text = "Options";
      toolTipItem4.LeftIndent = 6;
      toolTipItem4.Text = "Open the Print Options dialog, in which you can change printing options.";
      superToolTip4.Items.Add((BaseToolTipItem) toolTipTitleItem4);
      superToolTip4.Items.Add((BaseToolTipItem) toolTipItem4);
      superToolTip4.MaxWidth = 210;
      this.printPreviewBarItem4.SuperTip = superToolTip4;
      this.printPreviewBarItem5.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem5.Caption = "Print";
      this.printPreviewBarItem5.Command = PrintingSystemCommand.Print;
      this.printPreviewBarItem5.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem5.Enabled = false;
      this.printPreviewBarItem5.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Print;
      this.printPreviewBarItem5.Id = 4;
      this.printPreviewBarItem5.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PrintLarge;
      this.printPreviewBarItem5.Name = "printPreviewBarItem5";
      superToolTip5.FixedTooltipWidth = true;
      toolTipTitleItem5.Text = "Print (Ctrl+P)";
      toolTipItem5.LeftIndent = 6;
      toolTipItem5.Text = "Select a printer, number of copies and other printing options before printing.";
      superToolTip5.Items.Add((BaseToolTipItem) toolTipTitleItem5);
      superToolTip5.Items.Add((BaseToolTipItem) toolTipItem5);
      superToolTip5.MaxWidth = 210;
      this.printPreviewBarItem5.SuperTip = superToolTip5;
      this.printPreviewBarItem6.Caption = "Quick Print";
      this.printPreviewBarItem6.Command = PrintingSystemCommand.PrintDirect;
      this.printPreviewBarItem6.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem6.Enabled = false;
      this.printPreviewBarItem6.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PrintDirect;
      this.printPreviewBarItem6.Id = 5;
      this.printPreviewBarItem6.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PrintDirectLarge;
      this.printPreviewBarItem6.Name = "printPreviewBarItem6";
      superToolTip6.FixedTooltipWidth = true;
      toolTipTitleItem6.Text = "Quick Print";
      toolTipItem6.LeftIndent = 6;
      toolTipItem6.Text = "Send the document directly to the default printer without making changes.";
      superToolTip6.Items.Add((BaseToolTipItem) toolTipTitleItem6);
      superToolTip6.Items.Add((BaseToolTipItem) toolTipItem6);
      superToolTip6.MaxWidth = 210;
      this.printPreviewBarItem6.SuperTip = superToolTip6;
      this.printPreviewBarItem7.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem7.Caption = "Custom Margins...";
      this.printPreviewBarItem7.Command = PrintingSystemCommand.PageSetup;
      this.printPreviewBarItem7.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem7.Enabled = false;
      this.printPreviewBarItem7.Id = 6;
      this.printPreviewBarItem7.Name = "printPreviewBarItem7";
      superToolTip7.FixedTooltipWidth = true;
      toolTipTitleItem7.Text = "Page Setup";
      toolTipItem7.LeftIndent = 6;
      toolTipItem7.Text = "Show the Page Setup dialog.";
      superToolTip7.Items.Add((BaseToolTipItem) toolTipTitleItem7);
      superToolTip7.Items.Add((BaseToolTipItem) toolTipItem7);
      superToolTip7.MaxWidth = 210;
      this.printPreviewBarItem7.SuperTip = superToolTip7;
      this.printPreviewBarItem8.Caption = "Header/Footer";
      this.printPreviewBarItem8.Command = PrintingSystemCommand.EditPageHF;
      this.printPreviewBarItem8.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem8.Enabled = false;
      this.printPreviewBarItem8.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_EditPageHF;
      this.printPreviewBarItem8.Id = 7;
      this.printPreviewBarItem8.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_EditPageHFLarge;
      this.printPreviewBarItem8.Name = "printPreviewBarItem8";
      superToolTip8.FixedTooltipWidth = true;
      toolTipTitleItem8.Text = "Header and Footer";
      toolTipItem8.LeftIndent = 6;
      toolTipItem8.Text = "Edit the header and footer of the document.";
      superToolTip8.Items.Add((BaseToolTipItem) toolTipTitleItem8);
      superToolTip8.Items.Add((BaseToolTipItem) toolTipItem8);
      superToolTip8.MaxWidth = 210;
      this.printPreviewBarItem8.SuperTip = superToolTip8;
      this.printPreviewBarItem9.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem9.Caption = "Scale";
      this.printPreviewBarItem9.Command = PrintingSystemCommand.Scale;
      this.printPreviewBarItem9.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem9.Enabled = false;
      this.printPreviewBarItem9.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Scale;
      this.printPreviewBarItem9.Id = 8;
      this.printPreviewBarItem9.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ScaleLarge;
      this.printPreviewBarItem9.Name = "printPreviewBarItem9";
      superToolTip9.FixedTooltipWidth = true;
      toolTipTitleItem9.Text = "Scale";
      toolTipItem9.LeftIndent = 6;
      toolTipItem9.Text = "Stretch or shrink the printed output to a percentage of its actual size.";
      superToolTip9.Items.Add((BaseToolTipItem) toolTipTitleItem9);
      superToolTip9.Items.Add((BaseToolTipItem) toolTipItem9);
      superToolTip9.MaxWidth = 210;
      this.printPreviewBarItem9.SuperTip = superToolTip9;
      this.printPreviewBarItem10.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem10.Caption = "Pointer";
      this.printPreviewBarItem10.Command = PrintingSystemCommand.Pointer;
      this.printPreviewBarItem10.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem10.Down = true;
      this.printPreviewBarItem10.Enabled = false;
      this.printPreviewBarItem10.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Pointer;
      this.printPreviewBarItem10.GroupIndex = 1;
      this.printPreviewBarItem10.Id = 9;
      this.printPreviewBarItem10.Name = "printPreviewBarItem10";
      this.printPreviewBarItem10.RibbonStyle = RibbonItemStyles.SmallWithoutText;
      superToolTip10.FixedTooltipWidth = true;
      toolTipTitleItem10.Text = "Mouse Pointer";
      toolTipItem10.LeftIndent = 6;
      toolTipItem10.Text = "Show the mouse pointer.";
      superToolTip10.Items.Add((BaseToolTipItem) toolTipTitleItem10);
      superToolTip10.Items.Add((BaseToolTipItem) toolTipItem10);
      superToolTip10.MaxWidth = 210;
      this.printPreviewBarItem10.SuperTip = superToolTip10;
      this.printPreviewBarItem11.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem11.Caption = "Hand Tool";
      this.printPreviewBarItem11.Command = PrintingSystemCommand.HandTool;
      this.printPreviewBarItem11.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem11.Enabled = false;
      this.printPreviewBarItem11.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_HandTool;
      this.printPreviewBarItem11.GroupIndex = 1;
      this.printPreviewBarItem11.Id = 10;
      this.printPreviewBarItem11.Name = "printPreviewBarItem11";
      this.printPreviewBarItem11.RibbonStyle = RibbonItemStyles.SmallWithoutText;
      superToolTip11.FixedTooltipWidth = true;
      toolTipTitleItem11.Text = "Hand Tool";
      toolTipItem11.LeftIndent = 6;
      toolTipItem11.Text = "Invoke the Hand tool to manually scroll through pages.";
      superToolTip11.Items.Add((BaseToolTipItem) toolTipTitleItem11);
      superToolTip11.Items.Add((BaseToolTipItem) toolTipItem11);
      superToolTip11.MaxWidth = 210;
      this.printPreviewBarItem11.SuperTip = superToolTip11;
      this.printPreviewBarItem12.ButtonStyle = BarButtonStyle.Check;
      this.printPreviewBarItem12.Caption = "Magnifier";
      this.printPreviewBarItem12.Command = PrintingSystemCommand.Magnifier;
      this.printPreviewBarItem12.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem12.Enabled = false;
      this.printPreviewBarItem12.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Magnifier;
      this.printPreviewBarItem12.GroupIndex = 1;
      this.printPreviewBarItem12.Id = 11;
      this.printPreviewBarItem12.Name = "printPreviewBarItem12";
      this.printPreviewBarItem12.RibbonStyle = RibbonItemStyles.SmallWithoutText;
      superToolTip12.FixedTooltipWidth = true;
      toolTipTitleItem12.Text = "Magnifier";
      toolTipItem12.LeftIndent = 6;
      toolTipItem12.Text = "Invoke the Magnifier tool.\r\n\r\nClicking once on a document zooms it so that a single page becomes entirely visible, while clicking another time zooms it to 100% of the normal size.";
      superToolTip12.Items.Add((BaseToolTipItem) toolTipTitleItem12);
      superToolTip12.Items.Add((BaseToolTipItem) toolTipItem12);
      superToolTip12.MaxWidth = 210;
      this.printPreviewBarItem12.SuperTip = superToolTip12;
      this.printPreviewBarItem13.Caption = "Zoom Out";
      this.printPreviewBarItem13.Command = PrintingSystemCommand.ZoomOut;
      this.printPreviewBarItem13.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem13.Enabled = false;
      this.printPreviewBarItem13.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ZoomOut;
      this.printPreviewBarItem13.Id = 12;
      this.printPreviewBarItem13.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ZoomOutLarge;
      this.printPreviewBarItem13.Name = "printPreviewBarItem13";
      superToolTip13.FixedTooltipWidth = true;
      toolTipTitleItem13.Text = "Zoom Out";
      toolTipItem13.LeftIndent = 6;
      toolTipItem13.Text = "Zoom out to see more of the page at a reduced size.";
      superToolTip13.Items.Add((BaseToolTipItem) toolTipTitleItem13);
      superToolTip13.Items.Add((BaseToolTipItem) toolTipItem13);
      superToolTip13.MaxWidth = 210;
      this.printPreviewBarItem13.SuperTip = superToolTip13;
      this.printPreviewBarItem14.Caption = "Zoom In";
      this.printPreviewBarItem14.Command = PrintingSystemCommand.ZoomIn;
      this.printPreviewBarItem14.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem14.Enabled = false;
      this.printPreviewBarItem14.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ZoomIn;
      this.printPreviewBarItem14.Id = 13;
      this.printPreviewBarItem14.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ZoomInLarge;
      this.printPreviewBarItem14.Name = "printPreviewBarItem14";
      superToolTip14.FixedTooltipWidth = true;
      toolTipTitleItem14.Text = "Zoom In";
      toolTipItem14.LeftIndent = 6;
      toolTipItem14.Text = "Zoom in to get a close-up view of the document.";
      superToolTip14.Items.Add((BaseToolTipItem) toolTipTitleItem14);
      superToolTip14.Items.Add((BaseToolTipItem) toolTipItem14);
      superToolTip14.MaxWidth = 210;
      this.printPreviewBarItem14.SuperTip = superToolTip14;
      this.printPreviewBarItem15.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem15.Caption = "Zoom";
      this.printPreviewBarItem15.Command = PrintingSystemCommand.Zoom;
      this.printPreviewBarItem15.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem15.Enabled = false;
      this.printPreviewBarItem15.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Zoom;
      this.printPreviewBarItem15.Id = 14;
      this.printPreviewBarItem15.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ZoomLarge;
      this.printPreviewBarItem15.Name = "printPreviewBarItem15";
      superToolTip15.FixedTooltipWidth = true;
      toolTipTitleItem15.Text = "Zoom";
      toolTipItem15.LeftIndent = 6;
      toolTipItem15.Text = "Change the zoom level of the document preview.";
      superToolTip15.Items.Add((BaseToolTipItem) toolTipTitleItem15);
      superToolTip15.Items.Add((BaseToolTipItem) toolTipItem15);
      superToolTip15.MaxWidth = 210;
      this.printPreviewBarItem15.SuperTip = superToolTip15;
      this.printPreviewBarItem16.Caption = "First Page";
      this.printPreviewBarItem16.Command = PrintingSystemCommand.ShowFirstPage;
      this.printPreviewBarItem16.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem16.Enabled = false;
      this.printPreviewBarItem16.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowFirstPage;
      this.printPreviewBarItem16.Id = 15;
      this.printPreviewBarItem16.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowFirstPageLarge;
      this.printPreviewBarItem16.Name = "printPreviewBarItem16";
      superToolTip16.FixedTooltipWidth = true;
      toolTipTitleItem16.Text = "First Page (Ctrl+Home)";
      toolTipItem16.LeftIndent = 6;
      toolTipItem16.Text = "Navigate to the first page of the document.";
      superToolTip16.Items.Add((BaseToolTipItem) toolTipTitleItem16);
      superToolTip16.Items.Add((BaseToolTipItem) toolTipItem16);
      superToolTip16.MaxWidth = 210;
      this.printPreviewBarItem16.SuperTip = superToolTip16;
      this.printPreviewBarItem17.Caption = "Previous Page";
      this.printPreviewBarItem17.Command = PrintingSystemCommand.ShowPrevPage;
      this.printPreviewBarItem17.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem17.Enabled = false;
      this.printPreviewBarItem17.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowPrevPage;
      this.printPreviewBarItem17.Id = 16;
      this.printPreviewBarItem17.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowPrevPageLarge;
      this.printPreviewBarItem17.Name = "printPreviewBarItem17";
      superToolTip17.FixedTooltipWidth = true;
      toolTipTitleItem17.Text = "Previous Page (PageUp)";
      toolTipItem17.LeftIndent = 6;
      toolTipItem17.Text = "Navigate to the previous page of the document.";
      superToolTip17.Items.Add((BaseToolTipItem) toolTipTitleItem17);
      superToolTip17.Items.Add((BaseToolTipItem) toolTipItem17);
      superToolTip17.MaxWidth = 210;
      this.printPreviewBarItem17.SuperTip = superToolTip17;
      this.printPreviewBarItem18.Caption = "Next  Page ";
      this.printPreviewBarItem18.Command = PrintingSystemCommand.ShowNextPage;
      this.printPreviewBarItem18.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem18.Enabled = false;
      this.printPreviewBarItem18.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowNextPage;
      this.printPreviewBarItem18.Id = 17;
      this.printPreviewBarItem18.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowNextPageLarge;
      this.printPreviewBarItem18.Name = "printPreviewBarItem18";
      superToolTip18.FixedTooltipWidth = true;
      toolTipTitleItem18.Text = "Next Page (PageDown)";
      toolTipItem18.LeftIndent = 6;
      toolTipItem18.Text = "Navigate to the next page of the document.";
      superToolTip18.Items.Add((BaseToolTipItem) toolTipTitleItem18);
      superToolTip18.Items.Add((BaseToolTipItem) toolTipItem18);
      superToolTip18.MaxWidth = 210;
      this.printPreviewBarItem18.SuperTip = superToolTip18;
      this.printPreviewBarItem19.Caption = "Last  Page ";
      this.printPreviewBarItem19.Command = PrintingSystemCommand.ShowLastPage;
      this.printPreviewBarItem19.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem19.Enabled = false;
      this.printPreviewBarItem19.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowLastPage;
      this.printPreviewBarItem19.Id = 18;
      this.printPreviewBarItem19.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ShowLastPageLarge;
      this.printPreviewBarItem19.Name = "printPreviewBarItem19";
      superToolTip19.FixedTooltipWidth = true;
      toolTipTitleItem19.Text = "Last Page (Ctrl+End)";
      toolTipItem19.LeftIndent = 6;
      toolTipItem19.Text = "Navigate to the last page of the document.";
      superToolTip19.Items.Add((BaseToolTipItem) toolTipTitleItem19);
      superToolTip19.Items.Add((BaseToolTipItem) toolTipItem19);
      superToolTip19.MaxWidth = 210;
      this.printPreviewBarItem19.SuperTip = superToolTip19;
      this.printPreviewBarItem20.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem20.Caption = "Many Pages";
      this.printPreviewBarItem20.Command = PrintingSystemCommand.MultiplePages;
      this.printPreviewBarItem20.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem20.Enabled = false;
      this.printPreviewBarItem20.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_MultiplePages;
      this.printPreviewBarItem20.Id = 19;
      this.printPreviewBarItem20.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_MultiplePagesLarge;
      this.printPreviewBarItem20.Name = "printPreviewBarItem20";
      superToolTip20.FixedTooltipWidth = true;
      toolTipTitleItem20.Text = "View Many Pages";
      toolTipItem20.LeftIndent = 6;
      toolTipItem20.Text = "Choose the page layout to arrange the document pages in preview.";
      superToolTip20.Items.Add((BaseToolTipItem) toolTipTitleItem20);
      superToolTip20.Items.Add((BaseToolTipItem) toolTipItem20);
      superToolTip20.MaxWidth = 210;
      this.printPreviewBarItem20.SuperTip = superToolTip20;
      this.printPreviewBarItem21.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem21.Caption = "Page Color";
      this.printPreviewBarItem21.Command = PrintingSystemCommand.FillBackground;
      this.printPreviewBarItem21.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem21.Enabled = false;
      this.printPreviewBarItem21.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_FillBackground;
      this.printPreviewBarItem21.Id = 20;
      this.printPreviewBarItem21.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_FillBackgroundLarge;
      this.printPreviewBarItem21.Name = "printPreviewBarItem21";
      superToolTip21.FixedTooltipWidth = true;
      toolTipTitleItem21.Text = "Background Color";
      toolTipItem21.LeftIndent = 6;
      toolTipItem21.Text = "Choose a color for the background of the document pages.";
      superToolTip21.Items.Add((BaseToolTipItem) toolTipTitleItem21);
      superToolTip21.Items.Add((BaseToolTipItem) toolTipItem21);
      superToolTip21.MaxWidth = 210;
      this.printPreviewBarItem21.SuperTip = superToolTip21;
      this.printPreviewBarItem22.Caption = "Watermark";
      this.printPreviewBarItem22.Command = PrintingSystemCommand.Watermark;
      this.printPreviewBarItem22.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem22.Enabled = false;
      this.printPreviewBarItem22.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Watermark;
      this.printPreviewBarItem22.Id = 21;
      this.printPreviewBarItem22.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_WatermarkLarge;
      this.printPreviewBarItem22.Name = "printPreviewBarItem22";
      superToolTip22.FixedTooltipWidth = true;
      toolTipTitleItem22.Text = "Watermark";
      toolTipItem22.LeftIndent = 6;
      toolTipItem22.Text = "Insert ghosted text or image behind the content of a page.\r\n\r\nThis is often used to indicate that a document is to be treated specially.";
      superToolTip22.Items.Add((BaseToolTipItem) toolTipTitleItem22);
      superToolTip22.Items.Add((BaseToolTipItem) toolTipItem22);
      superToolTip22.MaxWidth = 210;
      this.printPreviewBarItem22.SuperTip = superToolTip22;
      this.printPreviewBarItem23.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem23.Caption = "Export To";
      this.printPreviewBarItem23.Command = PrintingSystemCommand.ExportFile;
      this.printPreviewBarItem23.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem23.Enabled = false;
      this.printPreviewBarItem23.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportFile;
      this.printPreviewBarItem23.Id = 22;
      this.printPreviewBarItem23.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportFileLarge;
      this.printPreviewBarItem23.Name = "printPreviewBarItem23";
      superToolTip23.FixedTooltipWidth = true;
      toolTipTitleItem23.Text = "Export To...";
      toolTipItem23.LeftIndent = 6;
      toolTipItem23.Text = "Export the current document in one of the available formats, and save it to the file on a disk.";
      superToolTip23.Items.Add((BaseToolTipItem) toolTipTitleItem23);
      superToolTip23.Items.Add((BaseToolTipItem) toolTipItem23);
      superToolTip23.MaxWidth = 210;
      this.printPreviewBarItem23.SuperTip = superToolTip23;
      this.printPreviewBarItem24.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem24.Caption = "E-Mail As";
      this.printPreviewBarItem24.Command = PrintingSystemCommand.SendFile;
      this.printPreviewBarItem24.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem24.Enabled = false;
      this.printPreviewBarItem24.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendFile;
      this.printPreviewBarItem24.Id = 23;
      this.printPreviewBarItem24.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendFileLarge;
      this.printPreviewBarItem24.Name = "printPreviewBarItem24";
      superToolTip24.FixedTooltipWidth = true;
      toolTipTitleItem24.Text = "E-Mail As...";
      toolTipItem24.LeftIndent = 6;
      toolTipItem24.Text = "Export the current document in one of the available formats, and attach it to the e-mail.";
      superToolTip24.Items.Add((BaseToolTipItem) toolTipTitleItem24);
      superToolTip24.Items.Add((BaseToolTipItem) toolTipItem24);
      superToolTip24.MaxWidth = 210;
      this.printPreviewBarItem24.SuperTip = superToolTip24;
      this.printPreviewBarItem25.Caption = "Close Print Preview";
      this.printPreviewBarItem25.Command = PrintingSystemCommand.ClosePreview;
      this.printPreviewBarItem25.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem25.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ClosePreview;
      this.printPreviewBarItem25.Id = 24;
      this.printPreviewBarItem25.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ClosePreviewLarge;
      this.printPreviewBarItem25.Name = "printPreviewBarItem25";
      superToolTip25.FixedTooltipWidth = true;
      toolTipTitleItem25.Text = "Close Print Preview";
      toolTipItem25.LeftIndent = 6;
      toolTipItem25.Text = "Close Print Preview of the document.";
      superToolTip25.Items.Add((BaseToolTipItem) toolTipTitleItem25);
      superToolTip25.Items.Add((BaseToolTipItem) toolTipItem25);
      superToolTip25.MaxWidth = 210;
      this.printPreviewBarItem25.SuperTip = superToolTip25;
      this.printPreviewBarItem26.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem26.Caption = "Orientation";
      this.printPreviewBarItem26.Command = PrintingSystemCommand.PageOrientation;
      this.printPreviewBarItem26.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem26.Enabled = false;
      this.printPreviewBarItem26.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageOrientation;
      this.printPreviewBarItem26.Id = 25;
      this.printPreviewBarItem26.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageOrientationLarge;
      this.printPreviewBarItem26.Name = "printPreviewBarItem26";
      superToolTip26.FixedTooltipWidth = true;
      toolTipTitleItem26.Text = "Page Orientation";
      toolTipItem26.LeftIndent = 6;
      toolTipItem26.Text = "Switch the pages between portrait and landscape layouts.";
      superToolTip26.Items.Add((BaseToolTipItem) toolTipTitleItem26);
      superToolTip26.Items.Add((BaseToolTipItem) toolTipItem26);
      superToolTip26.MaxWidth = 210;
      this.printPreviewBarItem26.SuperTip = superToolTip26;
      this.printPreviewBarItem27.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem27.Caption = "Size";
      this.printPreviewBarItem27.Command = PrintingSystemCommand.PaperSize;
      this.printPreviewBarItem27.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem27.Enabled = false;
      this.printPreviewBarItem27.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PaperSize;
      this.printPreviewBarItem27.Id = 26;
      this.printPreviewBarItem27.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PaperSizeLarge;
      this.printPreviewBarItem27.Name = "printPreviewBarItem27";
      superToolTip27.FixedTooltipWidth = true;
      toolTipTitleItem27.Text = "Page Size";
      toolTipItem27.LeftIndent = 6;
      toolTipItem27.Text = "Choose the paper size of the document.";
      superToolTip27.Items.Add((BaseToolTipItem) toolTipTitleItem27);
      superToolTip27.Items.Add((BaseToolTipItem) toolTipItem27);
      superToolTip27.MaxWidth = 210;
      this.printPreviewBarItem27.SuperTip = superToolTip27;
      this.printPreviewBarItem28.ButtonStyle = BarButtonStyle.DropDown;
      this.printPreviewBarItem28.Caption = "Margins";
      this.printPreviewBarItem28.Command = PrintingSystemCommand.PageMargins;
      this.printPreviewBarItem28.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem28.Enabled = false;
      this.printPreviewBarItem28.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageMargins;
      this.printPreviewBarItem28.Id = 27;
      this.printPreviewBarItem28.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageMarginsLarge;
      this.printPreviewBarItem28.Name = "printPreviewBarItem28";
      superToolTip28.FixedTooltipWidth = true;
      toolTipTitleItem28.Text = "Page Margins";
      toolTipItem28.LeftIndent = 6;
      toolTipItem28.Text = "Select the margin sizes for the entire document.\r\n\r\nTo apply specific margin sizes to the document, click Custom Margins.";
      superToolTip28.Items.Add((BaseToolTipItem) toolTipTitleItem28);
      superToolTip28.Items.Add((BaseToolTipItem) toolTipItem28);
      superToolTip28.MaxWidth = 210;
      this.printPreviewBarItem28.SuperTip = superToolTip28;
      this.printPreviewBarItem29.Caption = "PDF File";
      this.printPreviewBarItem29.Command = PrintingSystemCommand.SendPdf;
      this.printPreviewBarItem29.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem29.Description = "Adobe Portable Document Format";
      this.printPreviewBarItem29.Enabled = false;
      this.printPreviewBarItem29.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendPdf;
      this.printPreviewBarItem29.Id = 28;
      this.printPreviewBarItem29.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendPdfLarge;
      this.printPreviewBarItem29.Name = "printPreviewBarItem29";
      superToolTip29.FixedTooltipWidth = true;
      toolTipTitleItem29.Text = "E-Mail As PDF";
      toolTipItem29.LeftIndent = 6;
      toolTipItem29.Text = "Export the document to PDF and attach it to the e-mail.";
      superToolTip29.Items.Add((BaseToolTipItem) toolTipTitleItem29);
      superToolTip29.Items.Add((BaseToolTipItem) toolTipItem29);
      superToolTip29.MaxWidth = 210;
      this.printPreviewBarItem29.SuperTip = superToolTip29;
      this.printPreviewBarItem30.Caption = "Text File";
      this.printPreviewBarItem30.Command = PrintingSystemCommand.SendTxt;
      this.printPreviewBarItem30.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem30.Description = "Plain Text";
      this.printPreviewBarItem30.Enabled = false;
      this.printPreviewBarItem30.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendTxt;
      this.printPreviewBarItem30.Id = 29;
      this.printPreviewBarItem30.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendTxtLarge;
      this.printPreviewBarItem30.Name = "printPreviewBarItem30";
      superToolTip30.FixedTooltipWidth = true;
      toolTipTitleItem30.Text = "E-Mail As Text";
      toolTipItem30.LeftIndent = 6;
      toolTipItem30.Text = "Export the document to Text and attach it to the e-mail.";
      superToolTip30.Items.Add((BaseToolTipItem) toolTipTitleItem30);
      superToolTip30.Items.Add((BaseToolTipItem) toolTipItem30);
      superToolTip30.MaxWidth = 210;
      this.printPreviewBarItem30.SuperTip = superToolTip30;
      this.printPreviewBarItem31.Caption = "CSV File";
      this.printPreviewBarItem31.Command = PrintingSystemCommand.SendCsv;
      this.printPreviewBarItem31.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem31.Description = "Comma-Separated Values Text";
      this.printPreviewBarItem31.Enabled = false;
      this.printPreviewBarItem31.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendCsv;
      this.printPreviewBarItem31.Id = 30;
      this.printPreviewBarItem31.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendCsvLarge;
      this.printPreviewBarItem31.Name = "printPreviewBarItem31";
      superToolTip31.FixedTooltipWidth = true;
      toolTipTitleItem31.Text = "E-Mail As CSV";
      toolTipItem31.LeftIndent = 6;
      toolTipItem31.Text = "Export the document to CSV and attach it to the e-mail.";
      superToolTip31.Items.Add((BaseToolTipItem) toolTipTitleItem31);
      superToolTip31.Items.Add((BaseToolTipItem) toolTipItem31);
      superToolTip31.MaxWidth = 210;
      this.printPreviewBarItem31.SuperTip = superToolTip31;
      this.printPreviewBarItem32.Caption = "MHT File";
      this.printPreviewBarItem32.Command = PrintingSystemCommand.SendMht;
      this.printPreviewBarItem32.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem32.Description = "Single File Web Page";
      this.printPreviewBarItem32.Enabled = false;
      this.printPreviewBarItem32.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendMht;
      this.printPreviewBarItem32.Id = 31;
      this.printPreviewBarItem32.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendMhtLarge;
      this.printPreviewBarItem32.Name = "printPreviewBarItem32";
      superToolTip32.FixedTooltipWidth = true;
      toolTipTitleItem32.Text = "E-Mail As MHT";
      toolTipItem32.LeftIndent = 6;
      toolTipItem32.Text = "Export the document to MHT and attach it to the e-mail.";
      superToolTip32.Items.Add((BaseToolTipItem) toolTipTitleItem32);
      superToolTip32.Items.Add((BaseToolTipItem) toolTipItem32);
      superToolTip32.MaxWidth = 210;
      this.printPreviewBarItem32.SuperTip = superToolTip32;
      this.printPreviewBarItem33.Caption = "Excel File";
      this.printPreviewBarItem33.Command = PrintingSystemCommand.SendXls;
      this.printPreviewBarItem33.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem33.Description = "Microsoft Excel Workbook";
      this.printPreviewBarItem33.Enabled = false;
      this.printPreviewBarItem33.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendXls;
      this.printPreviewBarItem33.Id = 32;
      this.printPreviewBarItem33.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendXlsLarge;
      this.printPreviewBarItem33.Name = "printPreviewBarItem33";
      superToolTip33.FixedTooltipWidth = true;
      toolTipTitleItem33.Text = "E-Mail As XLS";
      toolTipItem33.LeftIndent = 6;
      toolTipItem33.Text = "Export the document to XLS and attach it to the e-mail.";
      superToolTip33.Items.Add((BaseToolTipItem) toolTipTitleItem33);
      superToolTip33.Items.Add((BaseToolTipItem) toolTipItem33);
      superToolTip33.MaxWidth = 210;
      this.printPreviewBarItem33.SuperTip = superToolTip33;
      this.printPreviewBarItem34.Caption = "RTF File";
      this.printPreviewBarItem34.Command = PrintingSystemCommand.SendRtf;
      this.printPreviewBarItem34.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem34.Description = "Rich Text Format";
      this.printPreviewBarItem34.Enabled = false;
      this.printPreviewBarItem34.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendRtf;
      this.printPreviewBarItem34.Id = 33;
      this.printPreviewBarItem34.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendRtfLarge;
      this.printPreviewBarItem34.Name = "printPreviewBarItem34";
      superToolTip34.FixedTooltipWidth = true;
      toolTipTitleItem34.Text = "E-Mail As RTF";
      toolTipItem34.LeftIndent = 6;
      toolTipItem34.Text = "Export the document to RTF and attach it to the e-mail.";
      superToolTip34.Items.Add((BaseToolTipItem) toolTipTitleItem34);
      superToolTip34.Items.Add((BaseToolTipItem) toolTipItem34);
      superToolTip34.MaxWidth = 210;
      this.printPreviewBarItem34.SuperTip = superToolTip34;
      this.printPreviewBarItem35.Caption = "Image File";
      this.printPreviewBarItem35.Command = PrintingSystemCommand.SendGraphic;
      this.printPreviewBarItem35.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem35.Description = "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
      this.printPreviewBarItem35.Enabled = false;
      this.printPreviewBarItem35.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendGraphic;
      this.printPreviewBarItem35.Id = 34;
      this.printPreviewBarItem35.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SendGraphicLarge;
      this.printPreviewBarItem35.Name = "printPreviewBarItem35";
      superToolTip35.FixedTooltipWidth = true;
      toolTipTitleItem35.Text = "E-Mail As Image";
      toolTipItem35.LeftIndent = 6;
      toolTipItem35.Text = "Export the document to Image and attach it to the e-mail.";
      superToolTip35.Items.Add((BaseToolTipItem) toolTipTitleItem35);
      superToolTip35.Items.Add((BaseToolTipItem) toolTipItem35);
      superToolTip35.MaxWidth = 210;
      this.printPreviewBarItem35.SuperTip = superToolTip35;
      this.printPreviewBarItem36.Caption = "PDF File";
      this.printPreviewBarItem36.Command = PrintingSystemCommand.ExportPdf;
      this.printPreviewBarItem36.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem36.Description = "Adobe Portable Document Format";
      this.printPreviewBarItem36.Enabled = false;
      this.printPreviewBarItem36.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportPdf;
      this.printPreviewBarItem36.Id = 35;
      this.printPreviewBarItem36.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportPdfLarge;
      this.printPreviewBarItem36.Name = "printPreviewBarItem36";
      superToolTip36.FixedTooltipWidth = true;
      toolTipTitleItem36.Text = "Export to PDF";
      toolTipItem36.LeftIndent = 6;
      toolTipItem36.Text = "Export the document to PDF and save it to the file on a disk.";
      superToolTip36.Items.Add((BaseToolTipItem) toolTipTitleItem36);
      superToolTip36.Items.Add((BaseToolTipItem) toolTipItem36);
      superToolTip36.MaxWidth = 210;
      this.printPreviewBarItem36.SuperTip = superToolTip36;
      this.printPreviewBarItem37.Caption = "HTML File";
      this.printPreviewBarItem37.Command = PrintingSystemCommand.ExportHtm;
      this.printPreviewBarItem37.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem37.Description = "Web Page";
      this.printPreviewBarItem37.Enabled = false;
      this.printPreviewBarItem37.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportHtm;
      this.printPreviewBarItem37.Id = 36;
      this.printPreviewBarItem37.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportHtmLarge;
      this.printPreviewBarItem37.Name = "printPreviewBarItem37";
      superToolTip37.FixedTooltipWidth = true;
      toolTipTitleItem37.Text = "Export to HTML";
      toolTipItem37.LeftIndent = 6;
      toolTipItem37.Text = "Export the document to HTML and save it to the file on a disk.";
      superToolTip37.Items.Add((BaseToolTipItem) toolTipTitleItem37);
      superToolTip37.Items.Add((BaseToolTipItem) toolTipItem37);
      superToolTip37.MaxWidth = 210;
      this.printPreviewBarItem37.SuperTip = superToolTip37;
      this.printPreviewBarItem38.Caption = "Text File";
      this.printPreviewBarItem38.Command = PrintingSystemCommand.ExportTxt;
      this.printPreviewBarItem38.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem38.Description = "Plain Text";
      this.printPreviewBarItem38.Enabled = false;
      this.printPreviewBarItem38.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportTxt;
      this.printPreviewBarItem38.Id = 37;
      this.printPreviewBarItem38.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportTxtLarge;
      this.printPreviewBarItem38.Name = "printPreviewBarItem38";
      superToolTip38.FixedTooltipWidth = true;
      toolTipTitleItem38.Text = "Export to Text";
      toolTipItem38.LeftIndent = 6;
      toolTipItem38.Text = "Export the document to Text and save it to the file on a disk.";
      superToolTip38.Items.Add((BaseToolTipItem) toolTipTitleItem38);
      superToolTip38.Items.Add((BaseToolTipItem) toolTipItem38);
      superToolTip38.MaxWidth = 210;
      this.printPreviewBarItem38.SuperTip = superToolTip38;
      this.printPreviewBarItem39.Caption = "CSV File";
      this.printPreviewBarItem39.Command = PrintingSystemCommand.ExportCsv;
      this.printPreviewBarItem39.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem39.Description = "Comma-Separated Values Text";
      this.printPreviewBarItem39.Enabled = false;
      this.printPreviewBarItem39.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportCsv;
      this.printPreviewBarItem39.Id = 38;
      this.printPreviewBarItem39.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportCsvLarge;
      this.printPreviewBarItem39.Name = "printPreviewBarItem39";
      superToolTip39.FixedTooltipWidth = true;
      toolTipTitleItem39.Text = "Export to CSV";
      toolTipItem39.LeftIndent = 6;
      toolTipItem39.Text = "Export the document to CSV and save it to the file on a disk.";
      superToolTip39.Items.Add((BaseToolTipItem) toolTipTitleItem39);
      superToolTip39.Items.Add((BaseToolTipItem) toolTipItem39);
      superToolTip39.MaxWidth = 210;
      this.printPreviewBarItem39.SuperTip = superToolTip39;
      this.printPreviewBarItem40.Caption = "MHT File";
      this.printPreviewBarItem40.Command = PrintingSystemCommand.ExportMht;
      this.printPreviewBarItem40.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem40.Description = "Single File Web Page";
      this.printPreviewBarItem40.Enabled = false;
      this.printPreviewBarItem40.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportMht;
      this.printPreviewBarItem40.Id = 39;
      this.printPreviewBarItem40.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportMhtLarge;
      this.printPreviewBarItem40.Name = "printPreviewBarItem40";
      superToolTip40.FixedTooltipWidth = true;
      toolTipTitleItem40.Text = "Export to MHT";
      toolTipItem40.LeftIndent = 6;
      toolTipItem40.Text = "Export the document to MHT and save it to the file on a disk.";
      superToolTip40.Items.Add((BaseToolTipItem) toolTipTitleItem40);
      superToolTip40.Items.Add((BaseToolTipItem) toolTipItem40);
      superToolTip40.MaxWidth = 210;
      this.printPreviewBarItem40.SuperTip = superToolTip40;
      this.printPreviewBarItem41.Caption = "Excel File";
      this.printPreviewBarItem41.Command = PrintingSystemCommand.ExportXls;
      this.printPreviewBarItem41.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem41.Description = "Microsoft Excel Workbook";
      this.printPreviewBarItem41.Enabled = false;
      this.printPreviewBarItem41.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportXls;
      this.printPreviewBarItem41.Id = 40;
      this.printPreviewBarItem41.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportXlsLarge;
      this.printPreviewBarItem41.Name = "printPreviewBarItem41";
      superToolTip41.FixedTooltipWidth = true;
      toolTipTitleItem41.Text = "Export to XLS";
      toolTipItem41.LeftIndent = 6;
      toolTipItem41.Text = "Export the document to XLS and save it to the file on a disk.";
      superToolTip41.Items.Add((BaseToolTipItem) toolTipTitleItem41);
      superToolTip41.Items.Add((BaseToolTipItem) toolTipItem41);
      superToolTip41.MaxWidth = 210;
      this.printPreviewBarItem41.SuperTip = superToolTip41;
      this.printPreviewBarItem42.Caption = "RTF File";
      this.printPreviewBarItem42.Command = PrintingSystemCommand.ExportRtf;
      this.printPreviewBarItem42.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem42.Description = "Rich Text Format";
      this.printPreviewBarItem42.Enabled = false;
      this.printPreviewBarItem42.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportRtf;
      this.printPreviewBarItem42.Id = 41;
      this.printPreviewBarItem42.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportRtfLarge;
      this.printPreviewBarItem42.Name = "printPreviewBarItem42";
      superToolTip42.FixedTooltipWidth = true;
      toolTipTitleItem42.Text = "Export to RTF";
      toolTipItem42.LeftIndent = 6;
      toolTipItem42.Text = "Export the document to RTF and save it to the file on a disk.";
      superToolTip42.Items.Add((BaseToolTipItem) toolTipTitleItem42);
      superToolTip42.Items.Add((BaseToolTipItem) toolTipItem42);
      superToolTip42.MaxWidth = 210;
      this.printPreviewBarItem42.SuperTip = superToolTip42;
      this.printPreviewBarItem43.Caption = "Image File";
      this.printPreviewBarItem43.Command = PrintingSystemCommand.ExportGraphic;
      this.printPreviewBarItem43.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem43.Description = "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
      this.printPreviewBarItem43.Enabled = false;
      this.printPreviewBarItem43.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportGraphic;
      this.printPreviewBarItem43.Id = 42;
      this.printPreviewBarItem43.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportGraphicLarge;
      this.printPreviewBarItem43.Name = "printPreviewBarItem43";
      superToolTip43.FixedTooltipWidth = true;
      toolTipTitleItem43.Text = "Export to Image";
      toolTipItem43.LeftIndent = 6;
      toolTipItem43.Text = "Export the document to Image and save it to the file on a disk.";
      superToolTip43.Items.Add((BaseToolTipItem) toolTipTitleItem43);
      superToolTip43.Items.Add((BaseToolTipItem) toolTipItem43);
      superToolTip43.MaxWidth = 210;
      this.printPreviewBarItem43.SuperTip = superToolTip43;
      this.printPreviewBarItem44.Caption = "Open";
      this.printPreviewBarItem44.Command = PrintingSystemCommand.Open;
      this.printPreviewBarItem44.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem44.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Open;
      this.printPreviewBarItem44.Id = 43;
      this.printPreviewBarItem44.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_OpenLarge;
      this.printPreviewBarItem44.Name = "printPreviewBarItem44";
      superToolTip44.FixedTooltipWidth = true;
      toolTipTitleItem44.Text = "Open (Ctrl + O)";
      toolTipItem44.LeftIndent = 6;
      toolTipItem44.Text = "Open a document.";
      superToolTip44.Items.Add((BaseToolTipItem) toolTipTitleItem44);
      superToolTip44.Items.Add((BaseToolTipItem) toolTipItem44);
      superToolTip44.MaxWidth = 210;
      this.printPreviewBarItem44.SuperTip = superToolTip44;
      this.printPreviewBarItem45.Caption = "Save";
      this.printPreviewBarItem45.Command = PrintingSystemCommand.Save;
      this.printPreviewBarItem45.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewBarItem45.Enabled = false;
      this.printPreviewBarItem45.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Save;
      this.printPreviewBarItem45.Id = 44;
      this.printPreviewBarItem45.LargeGlyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_SaveLarge;
      this.printPreviewBarItem45.Name = "printPreviewBarItem45";
      superToolTip45.FixedTooltipWidth = true;
      toolTipTitleItem45.Text = "Save (Ctrl + S)";
      toolTipItem45.LeftIndent = 6;
      toolTipItem45.Text = "Save the document.";
      superToolTip45.Items.Add((BaseToolTipItem) toolTipTitleItem45);
      superToolTip45.Items.Add((BaseToolTipItem) toolTipItem45);
      superToolTip45.MaxWidth = 210;
      this.printPreviewBarItem45.SuperTip = superToolTip45;
      this.printPreviewRibbonPage1.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPage1.Groups.AddRange(new RibbonPageGroup[7]
      {
        (RibbonPageGroup) this.printPreviewRibbonPageGroup1,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup2,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup3,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup4,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup5,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup6,
        (RibbonPageGroup) this.printPreviewRibbonPageGroup7
      });
      this.printPreviewRibbonPage1.KeyTip = "";
      this.printPreviewRibbonPage1.Name = "printPreviewRibbonPage1";
      this.printPreviewRibbonPage1.Text = "Print Preview";
      this.printPreviewRibbonPageGroup1.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup1.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Document;
      this.printPreviewRibbonPageGroup1.ItemLinks.Add((BarItem) this.printPreviewBarItem44);
      this.printPreviewRibbonPageGroup1.ItemLinks.Add((BarItem) this.printPreviewBarItem45);
      this.printPreviewRibbonPageGroup1.KeyTip = "";
      this.printPreviewRibbonPageGroup1.Kind = PrintPreviewRibbonPageGroupKind.Document;
      this.printPreviewRibbonPageGroup1.Name = "printPreviewRibbonPageGroup1";
      this.printPreviewRibbonPageGroup1.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup1.Text = "Document";
      this.printPreviewRibbonPageGroup2.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup2.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PrintDirect;
      this.printPreviewRibbonPageGroup2.ItemLinks.Add((BarItem) this.printPreviewBarItem5);
      this.printPreviewRibbonPageGroup2.ItemLinks.Add((BarItem) this.printPreviewBarItem6);
      this.printPreviewRibbonPageGroup2.ItemLinks.Add((BarItem) this.printPreviewBarItem4);
      this.printPreviewRibbonPageGroup2.ItemLinks.Add((BarItem) this.printPreviewBarItem2);
      this.printPreviewRibbonPageGroup2.KeyTip = "";
      this.printPreviewRibbonPageGroup2.Kind = PrintPreviewRibbonPageGroupKind.Print;
      this.printPreviewRibbonPageGroup2.Name = "printPreviewRibbonPageGroup2";
      this.printPreviewRibbonPageGroup2.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup2.Text = "Print";
      this.printPreviewRibbonPageGroup3.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup3.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageMargins;
      this.printPreviewRibbonPageGroup3.ItemLinks.Add((BarItem) this.printPreviewBarItem8);
      this.printPreviewRibbonPageGroup3.ItemLinks.Add((BarItem) this.printPreviewBarItem9);
      this.printPreviewRibbonPageGroup3.ItemLinks.Add((BarItem) this.printPreviewBarItem28);
      this.printPreviewRibbonPageGroup3.ItemLinks.Add((BarItem) this.printPreviewBarItem26);
      this.printPreviewRibbonPageGroup3.ItemLinks.Add((BarItem) this.printPreviewBarItem27);
      this.printPreviewRibbonPageGroup3.KeyTip = "";
      this.printPreviewRibbonPageGroup3.Kind = PrintPreviewRibbonPageGroupKind.PageSetup;
      this.printPreviewRibbonPageGroup3.Name = "printPreviewRibbonPageGroup3";
      superToolTip46.FixedTooltipWidth = true;
      toolTipTitleItem46.Text = "Page Setup";
      toolTipItem46.Appearance.Image = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageSetupDialog;
      toolTipItem46.Appearance.Options.UseImage = true;
      toolTipItem46.Image = (Image) PrintRibbonControllerResources.RibbonPrintPreview_PageSetupDialog;
      toolTipItem46.LeftIndent = 6;
      toolTipItem46.Text = "Show the Page Setup dialog.";
      superToolTip46.Items.Add((BaseToolTipItem) toolTipTitleItem46);
      superToolTip46.Items.Add((BaseToolTipItem) toolTipItem46);
      superToolTip46.MaxWidth = 318;
      this.printPreviewRibbonPageGroup3.SuperTip = superToolTip46;
      this.printPreviewRibbonPageGroup3.Text = "Page Setup";
      this.printPreviewRibbonPageGroup4.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup4.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Find;
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem3);
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem1);
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem16, true);
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem17);
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem18);
      this.printPreviewRibbonPageGroup4.ItemLinks.Add((BarItem) this.printPreviewBarItem19);
      this.printPreviewRibbonPageGroup4.KeyTip = "";
      this.printPreviewRibbonPageGroup4.Kind = PrintPreviewRibbonPageGroupKind.Navigation;
      this.printPreviewRibbonPageGroup4.Name = "printPreviewRibbonPageGroup4";
      this.printPreviewRibbonPageGroup4.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup4.Text = "Navigation";
      this.printPreviewRibbonPageGroup5.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup5.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Zoom;
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem10);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem11);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem12);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem20);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem13);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem15);
      this.printPreviewRibbonPageGroup5.ItemLinks.Add((BarItem) this.printPreviewBarItem14);
      this.printPreviewRibbonPageGroup5.KeyTip = "";
      this.printPreviewRibbonPageGroup5.Kind = PrintPreviewRibbonPageGroupKind.Zoom;
      this.printPreviewRibbonPageGroup5.Name = "printPreviewRibbonPageGroup5";
      this.printPreviewRibbonPageGroup5.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup5.Text = "Zoom";
      this.printPreviewRibbonPageGroup6.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup6.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_Watermark;
      this.printPreviewRibbonPageGroup6.ItemLinks.Add((BarItem) this.printPreviewBarItem21);
      this.printPreviewRibbonPageGroup6.ItemLinks.Add((BarItem) this.printPreviewBarItem22);
      this.printPreviewRibbonPageGroup6.KeyTip = "";
      this.printPreviewRibbonPageGroup6.Kind = PrintPreviewRibbonPageGroupKind.Background;
      this.printPreviewRibbonPageGroup6.Name = "printPreviewRibbonPageGroup6";
      this.printPreviewRibbonPageGroup6.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup6.Text = "Page Background";
      this.printPreviewRibbonPageGroup7.ContextSpecifier = (object) this.printRibbonController1;
      this.printPreviewRibbonPageGroup7.Glyph = (Image) PrintRibbonControllerResources.RibbonPrintPreview_ExportFile;
      this.printPreviewRibbonPageGroup7.ItemLinks.Add((BarItem) this.printPreviewBarItem23);
      this.printPreviewRibbonPageGroup7.ItemLinks.Add((BarItem) this.printPreviewBarItem24);
      this.printPreviewRibbonPageGroup7.ItemLinks.Add((BarItem) this.printPreviewBarItem25, true);
      this.printPreviewRibbonPageGroup7.KeyTip = "";
      this.printPreviewRibbonPageGroup7.Kind = PrintPreviewRibbonPageGroupKind.Export;
      this.printPreviewRibbonPageGroup7.Name = "printPreviewRibbonPageGroup7";
      this.printPreviewRibbonPageGroup7.ShowCaptionButton = false;
      this.printPreviewRibbonPageGroup7.Text = "Export";
      this.clientPanel.BorderStyle = BorderStyles.NoBorder;
      this.clientPanel.Controls.Add((Control) this.printControl1);
      this.clientPanel.Dock = DockStyle.Fill;
      this.clientPanel.Location = new Point(0, 143);
      this.clientPanel.Name = "clientPanel";
      this.clientPanel.Size = new Size(889, 439);
      this.clientPanel.TabIndex = 2;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(889, 607);
      this.Controls.Add((Control) this.clientPanel);
      this.Controls.Add((Control) this.ribbonStatusBar);
      this.Controls.Add((Control) this.ribbon);
      this.Name = "ReportPreviewDialog";
      this.Ribbon = this.ribbon;
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterParent;
      this.StatusBar = this.ribbonStatusBar;
      this.Text = "PrintPreviewDialog";
      this.printRibbonController1.EndInit();
      this.repositoryItemProgressBar1.EndInit();
      this.repositoryItemZoomTrackBar1.EndInit();
      this.clientPanel.EndInit();
      this.clientPanel.ResumeLayout(false);
      this.ResumeLayout(false);
    }
  }
}
